name: social_app
description: 儿童社交线下约玩 App UI Demo
publish_to: 'none'
version: 1.0.0+1
# env description
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/